### ISSUE TITLE
[QUESTION] How to save media id?

### ISSUE THREAD

**Issue by cod3rshotout** [sebastienheyd/boilerplate-media-manager#8]
Hi, thank you for this package first!

In my application I need to attach in a custom table the reference of some documents loaded with `boilerplate-media-manager`. The problem is that the user would be able to rename the documents, and consequently the saved reference (image name) would no longer be valid.
Could you please recommend me a way to keep track of the uploaded media?

I had thought of creating a table called "medias", every time a document is loaded, the package will generate a new record on this table. The record will contain the name of the image and its reference, eg:

    storage/eUuHDp2DPWzxuQ.jpg

In the "medias" table will be:

    id: 1
    name: test.png
    guid: eUuHDp2DPWzxuQ.jpg

In this way in the main grid it is always possible to change the name of the image, but the physical file is no longer touched.

What do you think?
I'm unfortunately not an expert in laravel, so I would need a hand to implement this thing.

Thank you

**Comment by sebastienheyd** [comment]
Hi, thanks for your support.

I think unfortunately that you have to create your own upload / update method to send and rename the document because boilerplate-media-manager only work with native files and not virtual ones.

Maybe you can directly rename the native file and save the new name in the corresponding row in the database?
